baseURL: 'https://acsweb.ucsd.edu/~yaz093/'
title: Home | Yanbo Zhou
author: Yanbo Zhou
languageCode: en-us
pygmentsCodeFences: true
enableRobotsTXT: true
theme: hugo-flex
publishDir: docs

permalinks:
  posts: '/:filename/'
  pages: '/:filename/'

params:
  #color: "#005587"
  color: "#000000"
  width: 61rem
  description: Yanbo Zhou's webpages
  #footer: Except where otherwise noted, content on this site is licensed under a
  #  <a href="http://creativecommons.org/licenses/by/4.0/" rel="license">
  #  Creative Commons Attribution 4.0 International License</a>.
  footer: Updated in 2025.
  rss: >-
    To subscribe to this RSS feed, copy the address in the address bar and paste
    it into your favorite feed reader.
  divider: '\2015\2015' # Set to false to remove divider below posts on homepage
  schema: true
  opengraph: true
  twittercards: true
  summaries: false
  utterances:
    repo:               # Set to Utterances repo URL to add Utterances comments
    issueterm: pathname
    theme: github-light
  netlify:
    honeypot: false     # Set to true to add honeypot field in contact form
    recaptcha: false    # Set to true to add recaptcha challenge in contact form
  css:
    - custom.css
  # js:                 # Uncomment to add custom JS from a list of files
  #   - js/foo.js
  #   - bar.js

menu:
  nav:
    - name: Publications
      url: "#publications"
      weight: 1
    - name: Talks
      url: "#invited-talks"
      weight: 2
    - name: Books
      url: "#book-chapters"
      weight: 3